const countryNames = {
    AF: "Afghanistan",
    AL: "Albania",
    DZ: "Algeria",
    AR: "Argentina",
    AU: "Australia",
    AT: "Austria",
    BD: "Bangladesh",
    BE: "Belgium",
    BR: "Brazil",
    BG: "Bulgaria",
    CA: "Canada",
    CN: "China",
    CO: "Colombia",
    HR: "Croatia",
    CZ: "Czech Republic",
    DK: "Denmark",
    EG: "Egypt",
    FI: "Finland",
    FR: "France",
    DE: "Germany",
    GR: "Greece",
    HK: "Hong Kong",
    HU: "Hungary",
    IN: "India",
    ID: "Indonesia",
    IR: "Iran",
    IQ: "Iraq",
    IE: "Ireland",
    IL: "Israel",
    IT: "Italy",
    JP: "Japan",
    JO: "Jordan",
    KE: "Kenya",
    KR: "South Korea",
    KW: "Kuwait",
    LB: "Lebanon",
    LY: "Libya",
    MY: "Malaysia",
    MX: "Mexico",
    MA: "Morocco",
    NL: "Netherlands",
    NZ: "New Zealand",
    NG: "Nigeria",
    NO: "Norway",
    PK: "Pakistan",
    PH: "Philippines",
    PL: "Poland",
    PT: "Portugal",
    PG: "Papua New Guinea",
    QA: "Qatar",
    RO: "Romania",
    RU: "Russia",
    SA: "Saudi Arabia",
    RS: "Serbia",
    SG: "Singapore",
    ZA: "South Africa",
    ES: "Spain",
    LK: "Sri Lanka",
    SE: "Sweden",
    CH: "Switzerland",
    SY: "Syria",
    TW: "Taiwan",
    TH: "Thailand",
    TN: "Tunisia",
    TR: "Turkey",
    UA: "Ukraine",
    AE: "United Arab Emirates",
    GB: "United Kingdom",
    US: "United States",
    VN: "Vietnam",
    YE: "Yemen"
};

export default countryNames;